stages:
  - test
  - staging
  - production

testing:
  stage: test
  tags:
    - testing
  only:
    - merge_request
  before_script:
    - cp $ENV_TESTING $CI_PROJECT_DIR/.env
  script:
    - docker compose --profile testing up --build --abort-on-container-exit

staging:
  stage: staging
  tags:
    - staging
  environment: staging
  only:
    - staging
  before_script:
    - cp $ENV_STAGING $CI_PROJECT_DIR/.env
  script:
    - docker compose --profile staging up --build --wait

production:
  stage: production
  tags:
    - production
  environment: production
  only:
    - tag
  before_script:
    - cp $ENV_STAGING $CI_PROJECT_DIR/.env
  script:
    - docker compose --profile production up --build --wait
