version: "3.8"

volumes:
  postgres_data: {}
  storage_data: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}
  postgresql: {}
  postgresql_data: {}

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: src/.env

  django:
    build:
      context: .
      dockerfile: ./package/Dockerfile
    volumes:
      - storage_data:/src/media
    depends_on:
      - postgres
    env_file: src/.env
    ports:
      - "9000:9000"
    links:
      - postgres

  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
