volumes:
  postgres_data: {}
  storage_data: {}
  storage_logs: {}

services:
  db_testing:
    image: postgres:latest
    profiles:
      - testing
    env_file: .env
    container_name: db_testing
    healthcheck:
      test: sh -c 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB'
      interval: 30s
      timeout: 5s
      retries: 5

  web_testing:
    build:
      context: .
      dockerfile: ./package/Dockerfile
    profiles:
      - testing
    env_file: .env
    container_name: web_testing
    depends_on:
      postgres_testing:
        condition: service_healthy
    links:
      - "db_testing:database"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    container_name: db
    healthcheck:
      test: sh -c 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB'
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build:
      context: .
      dockerfile: ./packaging/staging/Dockerfile
    container_name: web
    volumes:
      - web_media:/src/media:rw
      - web_logs:/src/logging:rw
    depends_on:
      postgres_staging:
        condition: service_healthy
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    links:
      - "db:database"
