[tool.poetry]
name = "django-template"
version = "0.1.0"
description = ""
authors = ["BeemenSameh <41084077+BeemenSameh@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0"
djangorestframework = "^3.12.4"
django-environ = "^0.8.1"
psycopg2 = "^2.9.2"
gunicorn = "^20.1.0"
uWSGI = "^2.0.20"

[tool.poetry.dev-dependencies]
drf-yasg = "^1.20.0"
docutils = "^0.18"
isort = "^5.10.1"
pytest-django = "^4.5.2"
django-extensions = "^3.1.5"
ipython = "^7.30.1"
coverage = "^6.2"
autopep8 = "^1.6.0"
django-debug-toolbar = "^3.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
