[tool.poetry]
name = "{{project_name}}"
version = "0.1.0"
description = ""
authors = ["Beemen Sameh <41084077+BeemenSameh@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "3.2.4"
djangorestframework = "3.12.4"
django-environ = "^0.4.5"
psycopg2 = "^2.8.6"
gunicorn = "^20.1.0"
uWSGI = "^2.0.19"

[tool.poetry.dev-dependencies]
drf-yasg = "1.20.0"
docutils = "0.17.1"
flake8 = "^3.9.2"
isort = "^5.8.0"
pytest-django = "^4.4.0"
django-queryinspect = "^1.1.0"
django-extensions = "^3.1.3"
ipython = "^7.24.1"
coverage = "^5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
