[tool.poetry]
name = "django-template"
version = "0.1.0"
description = ""
authors = ["BeemenSameh <41084077+BeemenSameh@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.1"
djangorestframework = "^3.14"
django-environ = "^0.9"
psycopg2 = "^2.9"
gunicorn = "^20.1"
uWSGI = "^2.0"
django-extensions = "^3.2"

[tool.poetry.dev-dependencies]
drf-yasg = "^1.21"
docutils = "^0.19"
isort = "^5.10"
pytest-django = "^4.5"
ipython = "^8.5"
coverage = "^6.4"
autopep8 = "^1.7"
django-debug-toolbar = "^3.6"
flake8 = "^5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
