[tool.poetry]
name = "django-template"
version = "0.1.0"
description = ""
authors = ["BeemenSameh <41084077+BeemenSameh@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0"
djangorestframework = "^3.12"
django-environ = "^0.9"
psycopg2 = "^2.9"
gunicorn = "^20.1"
uWSGI = "^2.0"
django-extensions = "^3.2.0"

[tool.poetry.dev-dependencies]
drf-yasg = "^1.20"
docutils = "^0.19"
isort = "^5.10"
pytest-django = "^4.5"
ipython = "^8.4"
coverage = "^6.4"
autopep8 = "^1.6"
django-debug-toolbar = "^3.5"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
